digitalocean:
  service: S3
  endpoint: https://cdn.dev.petlo.co
  access_key_id: <%= Rails.application.credentials[:digitalocean][:development][:space][:access_key] %>
  secret_access_key: <%= Rails.application.credentials[:digitalocean][:development][:space][:secret__key] %>
  bucket: petlo-development
  region: unused
