import { LANGUAGES_OPTIONS } from "./LANGUAGES_OPTIONS";
import { LANGUAGE_ADJECTIVES_OPTIONS } from "./LANGUAGE_ADJECTIVES_OPTIONS";
import { COUNTRIES_OPTIONS } from "./COUNTRIES_OPTIONS";
import { COUNTIES_PHONE_CODE_OPTIONS } from "./COUNTIES_PHONE_CODE_OPTIONS";
import { DEFAULT_APP_LANGUAGE } from "./DEFAULT_APP_LANGUAGE";
import { VERIFICATION_CODE_LENGTH } from "./VERIFICATION_CODE_LENGTH";
import { MENU_PATHS } from "./MENU_PATHS";
import { HEDER_PATHS } from "./HEDER_PATHS";
import { MENU_TABS } from "./MENU_TABS";
import { HEDER_ICONS } from "./HEDER_ICONS";
import { MORE_PAGE_SECTIONS } from "./MORE_PAGE_SECTIONS";
import { PETS_GENDERS } from "./PETS_GENDERS";

export {
  LANGUAGES_OPTIONS,
  LANGUAGE_ADJECTIVES_OPTIONS,
  COUNTRIES_OPTIONS,
  COUNTIES_PHONE_CODE_OPTIONS,
  DEFAULT_APP_LANGUAGE,
  VERIFICATION_CODE_LENGTH,
  MENU_PATHS,
  HEDER_PATHS,
  MENU_TABS,
  HEDER_ICONS,
  MORE_PAGE_SECTIONS,
  PETS_GENDERS,
};
