import { LANGUAGES_OPTIONS } from "./LANGUAGES_OPTIONS";
import { LANGUAGE_ADJECTIVES_OPTIONS } from "./LANGUAGE_ADJECTIVES_OPTIONS";
import { COUNTRIES_OPTIONS } from "./COUNTRIES_OPTIONS";
import { COUNTIES_PHONE_CODE_OPTIONS } from "./COUNTIES_PHONE_CODE_OPTIONS";
import { DEFAULT_APP_LANGUAGE } from "./DEFAULT_APP_LANGUAGE";
import { VERIFICATION_CODE_LENGTH } from "./VERIFICATION_CODE_LENGTH";
import { MENU_PATHS } from "./MENU_PATHS";
import { HEDER_PATHS } from "./HEDER_PATHS";

export {
  LANGUAGES_OPTIONS,
  LANGUAGE_ADJECTIVES_OPTIONS,
  COUNTRIES_OPTIONS,
  COUNTIES_PHONE_CODE_OPTIONS,
  DEFAULT_APP_LANGUAGE,
  VERIFICATION_CODE_LENGTH,
  MENU_PATHS,
  HEDER_PATHS,
};
