export enum Endpoints {
  NEW_VERSION_AVAILABLE = "/v1/apps/new-version-available",
  CHECK_SESSION = "/v1/sessions",
  CREATE_NEW_CUSTOMER = "/v1/customers",
  VERIFY_CUSTOMER_ACCOUNT = "/v1/customers/verification",
  RESEND_VERIFICATION_CODE = "/v1/customers/verification/resend-code",
  EDIT_PHONE_NUMBER_ON_VERIFICATION = "/v1/customers/verification/change-phone-number",
  CREATE_SESSION = "/v1/sessions",
  VERIFY_SIGN_IN = "/v1/sessions/verification",
  RESEND_VERIFICATION_CODE_ON_VERIFY_SIGN_IN = "/v1/sessions/verification/resend-code",
  REQUEST_RESET_PASSWORD = "/v1/customers/request-reset-password",
  RESEND_RESET_PASSWORD_CODE = "/v1/customers/resend-reset-password-code",
  REQUEST_RESET_PASSWORD_VERIFICATION = "/v1/customers/verify-reset-password-request",
  RESET_PASSWORD = "/v1/customers/reset-password",
  CUSTOMER_INFORMATIONS = "/v1/customers",
  REQUEST_OTP_PERMISSION = "/v1/customers/request-permission-with-otp",
  DELETE_CUSTOMER = "/v1/customers",
  CHANGE_CUSTOMER_NAME = "/v1/customers/name",
  REQUEST_PASSWORD_PERMISSION = "/v1/customers/request-permission-with-password",
  CHANGE_CUSTOMER_PHONE_NUMBER = "/v1/customers/phone-number",
  VERIFY_REQUESTED_OTP_PERMISSION = "/v1/customers/verify-requested-permission-with-otp",
  CHANGE_CUSTOMER_PASSWORD = "/v1/customers/password",
  ADD_NEW_CARD = "/v1/cards",
  CUSTOMER_CARDS = "/v1/cards",
  PETS_INFORMATION = "/v1/pets/information",
  ADD_NEW_PET = "/v1/pets",
}
